# Generated by Django 5.2.6 on 2026-04-23 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="photo",
            field=models.ImageField(
                blank=True,
                default="users/default.jpg",
                null=True,
                upload_to="users/%Y/%m/%d/",
                verbose_name="Фото",
            ),
        ),
    ]
